$terminal = kitty

# Scripts programs
$clipboard = ~/.config/rofi/clipboard/launcher.sh
$shotcut = ~/.config/rofi/shotcut/script.sh
$wifi = ~/.config/rofi/wifi/wifi.sh
$launcher = ~/.config/rofi/launcher/launcher.sh
$switchLayouts = ~/.config/hypr/scripts/switch_layouts.sh

# Apps
$browser = firefox
$audio = pavucontrol
$lock = hyprlock
$fileManager = thunar
$logout = wlogout

# extra
$screenshot = grim -g "$(slurp)" - | satty --filename -
